---
- name: "Create a password file for the key of the certificate"
  copy:
    content: "{{ ssl.key_password }}"
    dest: "/var/lib/nginx/{{ ssl.key | basename }}.txt"
    owner: "{{ user }}"
  become: true
  when: ssl.enabled and ssl.key_password | length > 0

- name: "Configure Nginx as Reverse proxy to HTTPS"
  template:
    src: "https_reverse_proxy-nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  become: true
  when: "configuration == 'HTTPS-reverse-proxy'"
  notify: "Restart Nginx"
