---
- name: "Start Nginx"
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: "Restart Nginx"
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: true

- name: "Stop Nginx"
  systemd:
    name: nginx
    state: stopped
  become: true
